name: 'Falcon Site settings feature'
description: 'Configurations related to site settings.'
type: module
core: 8.x
dependencies:
  - config_pages
  - entity_reference_revisions
  - falcon_feature_content_blocks
  - falcon_feature_site_settings
  - field
  - field_group
  - file
  - image
  - link
  - media_library
  - menu_link_config
  - paragraphs
  - text
version: 8.x-1.1
package: Falcon
